Import("env")

env.Default(
    env.Program(
        'timer0_mode0_1T_sync_example',
        ['timer0_mode0_1T_sync_example.c']
    ),

    env.Program(
        'timer0_mode0_12T_sync_example',
        ['timer0_mode0_12T_sync_example.c']
    ),
)