Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

uart_example_prog = env.Program(
    'uart_example',
    ['uart_example.c', 'uart.c']
)

env.Default(uart_example_prog)

Return(['uart_example_prog'])
