Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

comparator_async_prog = env.Program(
    'comparator_async_example',
    ['comparator_async_example.c']
)

env.Default(comparator_async_prog)

Return(['comparator_async_prog'])
