Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

bits_prog = env.Program('bits_example', ['bits_example.c', 'uart.c'])
env.Default (
    bits_prog
)

Return('bits_prog')