Import("env")

timer_common_SConscript = SConscript('common/SConscript', exports = 'env')
timer_mode0_SConscript = SConscript('mode0/SConscript', exports = 'env')
timer_mode1_SConscript = SConscript('mode1/SConscript', exports = 'env')
timer_mode2_SConscript = SConscript('mode2/SConscript', exports = 'env')
timer_mode3_SConscript = SConscript('mode3/SConscript', exports = 'env')

Return([
    'timer_common_SConscript',
    'timer_mode0_SConscript',
    'timer_mode1_SConscript',
    'timer_mode2_SConscript',
    'timer_mode3_SConscript'
])
