Import("env")

counter0_prog = SConscript('counter0/SConscript', exports = 'env')
counter2_prog = SConscript('counter2/SConscript', exports = 'env')

Return([
    'counter0_prog',
    'counter2_prog',
])