Import('env')

env.Default(
    env.Program(
        'uart1_mode3_timer2_12T_example',
        ['uart1_mode3_timer2_12T_example.c']
    ),

    env.Program(
        'uart1_mode3_timer2_12T_freq_bias_example',
        ['uart1_mode3_timer2_12T_freq_bias_example.c']
    ),

    env.Program(
        'uart1_mode3_timer2_12T_interrupt_example',
        ['uart1_mode3_timer2_12T_interrupt_example.c']
    ),

    env.Program(
        'uart1_mode3_timer2_1T_example',
        ['uart1_mode3_timer2_1T_example.c']
    ),

    env.Program(
        'uart1_mode3_timer2_1T_freq_bias_example',
        ['uart1_mode3_timer2_1T_freq_bias_example.c']
    ),

    env.Program(
        'uart1_mode3_timer2_12T_even_parity_example',
        ['uart1_mode3_timer2_12T_even_parity_example.c']
    ),

    env.Program(
        'uart1_mode3_timer2_1T_odd_parity_example',
        ['uart1_mode3_timer2_1T_odd_parity_example.c']
    ),

)