Import("env")

uart1_mode3_timer2_12T_prog = env.Program(
    'uart1_mode3_timer2_12T_example',
    ['uart1_mode3_timer2_12T_example.c']
)

uart1_mode3_timer2_12T_freq_bias_prog = env.Program(
    'uart1_mode3_timer2_12T_freq_bias_example',
    ['uart1_mode3_timer2_12T_freq_bias_example.c']
)

uart1_mode3_timer2_12T_interrupt_prog = env.Program(
    'uart1_mode3_timer2_12T_interrupt_example',
    ['uart1_mode3_timer2_12T_interrupt_example.c']
)

uart1_mode3_timer2_1T_prog = env.Program(
    'uart1_mode3_timer2_1T_example',
    ['uart1_mode3_timer2_1T_example.c']
)

uart1_mode3_timer2_1T_freq_bias_prog = env.Program(
    'uart1_mode3_timer2_1T_freq_bias_example',
    ['uart1_mode3_timer2_1T_freq_bias_example.c']
)

uart1_mode3_timer2_12T_even_parity_prog = env.Program(
    'uart1_mode3_timer2_12T_even_parity_example',
    ['uart1_mode3_timer2_12T_even_parity_example.c']
)

uart1_mode3_timer2_1T_odd_parity_prog = env.Program(
    'uart1_mode3_timer2_1T_odd_parity_example',
    ['uart1_mode3_timer2_1T_odd_parity_example.c']
)

uart1_mode3_timer2_12T_receive_odd_parity_prog = env.Program(
    'uart1_mode3_timer2_12T_receive_odd_parity_example',
    ['uart1_mode3_timer2_12T_receive_odd_parity_example.c']
)

uart1_mode3_timer2_1T_2stop_bits_prog = env.Program(
    'uart1_mode3_timer2_1T_2stop_bits_example',
    ['uart1_mode3_timer2_1T_2stop_bits_example.c']
)

uart1_mode3_timer2_12T_space_parity_prog = env.Program(
    'uart1_mode3_timer2_12T_space_parity_example',
    ['uart1_mode3_timer2_12T_space_parity_example.c']
)

uart1_mode3_timer2_12T_receive_even_parity_prog = env.Program(
    'uart1_mode3_timer2_12T_receive_even_parity_example',
    ['uart1_mode3_timer2_12T_receive_even_parity_example.c']
)

env.Default(
    uart1_mode3_timer2_12T_prog,
    uart1_mode3_timer2_12T_freq_bias_prog,
    uart1_mode3_timer2_12T_interrupt_prog,
    uart1_mode3_timer2_1T_prog,
    uart1_mode3_timer2_1T_freq_bias_prog,
    uart1_mode3_timer2_12T_even_parity_prog,
    uart1_mode3_timer2_1T_odd_parity_prog,
    uart1_mode3_timer2_12T_receive_odd_parity_prog,
    uart1_mode3_timer2_1T_2stop_bits_prog,
    uart1_mode3_timer2_12T_space_parity_prog,
    uart1_mode3_timer2_12T_receive_even_parity_prog
)

Return([
    'uart1_mode3_timer2_12T_prog',
    'uart1_mode3_timer2_12T_freq_bias_prog',
    'uart1_mode3_timer2_12T_interrupt_prog',
    'uart1_mode3_timer2_1T_prog',
    'uart1_mode3_timer2_1T_freq_bias_prog',
    'uart1_mode3_timer2_12T_even_parity_prog',
    'uart1_mode3_timer2_1T_odd_parity_prog',
    'uart1_mode3_timer2_12T_receive_odd_parity_prog',
    'uart1_mode3_timer2_1T_2stop_bits_prog',
    'uart1_mode3_timer2_12T_space_parity_prog',
    'uart1_mode3_timer2_12T_receive_even_parity_prog'
])
