Import("env")

timer0_mode2_async_SConscript = SConscript('async/SConscript', exports = 'env')
timer0_mode2_sync_SConscript = SConscript('sync/SConscript', exports = 'env')
timer0_mode2_ms_freq_SConscript = SConscript('ms_freq/SConscript', exports = 'env')

Return([
    'timer0_mode2_async_SConscript',
    'timer0_mode2_sync_SConscript',
    'timer0_mode2_ms_freq_SConscript'
])
