Import("env")

env.Default(
    env.Object(
        source = 'pin_quasi_bidiretional_init_example.c',
        target = 'pin_quasi_bidiretional_init_example.rel'
    ),

    env.Object(
        source = 'pin_push_pull_init_example.c',
        target = 'pin_push_pull_init_example.rel'
    ),

    env.Object(
        source = 'pin_input_only_init_example.c',
        target = 'pin_input_only_init_example.rel'
    ),
)