Import("env")

env.Default(
    env.Program(
        'pin_quasi_bidiretional_init_example',
        ['pin_quasi_bidiretional_init_example.c', 'uart.c']
    ),

    env.Program(
        'pin_push_pull_init_example',
        ['pin_push_pull_init_example.c', 'uart.c']
    ),

    env.Program(
        'pin_input_only_init_example',
        ['pin_input_only_init_example.c', 'uart.c']
    ),

    env.Program(
        'pin_open_drain_init_example',
        ['pin_open_drain_init_example.c', 'uart.c']
    ),

    env.Program(
        'pin_mode_example',
        ['pin_mode_example.c', 'uart.c']
    ),
)