Import("env")

env.Default(
    env.Program(
        'pin_quasi_bidiretional_init_example',
        ['pin_quasi_bidiretional_init_example.c', 'uart.c']
    ),

    env.Program(
        'pin_push_pull_init_example',
        ['pin_push_pull_init_example.c', 'uart.c']
    ),

    env.Object(
        source = 'pin_input_only_init_example.c',
        target = 'pin_input_only_init_example.rel'
    ),

    env.Object(
        source = 'pin_open_drain_init_example.c',
        target = 'pin_open_drain_init_example.rel'
    ),

    env.Object(
        source = 'pin_mode_example.c',
        target = 'pin_mode_example.rel'
    ),

    env.Object(
        source = 'port_mode_init_example.c',
        target = 'port_mode_init_example.rel'
    ),

)