Import('env')

env.Default(
    env.Program(
        'timer0_mode3_1T_interrupt_example',
        ['timer0_mode3_1T_interrupt_example.c']
    ),

    env.Object(
        source = 'timer0_mode3_pause_by_gate_example.c',
        target = 'timer0_mode3_pause_by_gate_example.rel'
    ),

    env.Object(
        source = 'timer0_mode3_reload_example.c',
        target = 'timer0_mode3_reload_example.rel'
    ),

    env.Object(
        source = 'timer0_mode3_direct_reload_example.c',
        target = 'timer0_mode3_direct_reload_example.rel'
    ),

    env.Object(
        source = 'timer0_mode3_direct_start_example.c',
        target = 'timer0_mode3_direct_start_example.rel'
    ),

    env.Object(
        source = 'timer2_mode0_direct_start_example.c',
        target = 'timer2_mode3_direct_start_example.rel'
    ),
)