Import('env')

env.Default(
    env.Program(
        'timer0_mode3_1T_interrupt_example',
        ['timer0_mode3_1T_interrupt_example.c']
    ),

    env.Program(
        'timer0_mode3_pause_by_gate_example',
        ['timer0_mode3_pause_by_gate_example.c']
    ),

    env.Program(
        'timer0_mode3_reload_example',
        ['timer0_mode3_reload_example.c']
    ),

    env.Program(
        'timer0_mode3_direct_reload_example',
        ['timer0_mode3_direct_reload_example.c']
    ),

    env.Program(
        'timer0_mode3_direct_start_example',
        ['timer0_mode3_direct_start_example.c']
    ),

)