Import("env")

env.Default (
    env.Program(
        'counter0_mode0_example', 
        [
            'counter0_mode0_example.c', 
            'uart.c'
        ]
    ), 

    env.Program(
        'counter0_mode0_p35_output_example',
        ['counter0_mode0_p35_output_example.c']
    ),

    env.Program(
        'counter0_mode0_gate_example',
        ['counter0_mode0_gate_example.c']
    )
)