Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))
env.Command('ms_to_ticks_common.c', '#src/ms_to_ticks_common.c', Copy('$TARGET', '$SOURCE'))
env.Command('ticks_to_ms_common.c', '#src/ticks_to_ms_common.c', Copy('$TARGET', '$SOURCE'))
env.Command('timer_ticks_to_Hz.c', '#src/timer_ticks_to_Hz.c', Copy('$TARGET', '$SOURCE'))

env.Default(
    env.Program(
        'timer0_mode0_ms_to_ticks_example',
        ['timer0_mode0_ms_to_ticks_example.c', 'uart.c', 'ms_to_ticks_common.c']
    ),
    env.Program(
        'timer0_mode0_ticks_to_ms_example',
        ['timer0_mode0_ticks_to_ms_example.c', 'uart.c', 'ticks_to_ms_common.c']
    ),
    env.Program(
        'timer0_mode0_ticks_to_Hz_example',
        ['timer0_mode0_ticks_to_Hz_example.c', 'uart.c', 'timer_ticks_to_Hz.c']
    ),    
)
