Import("env")

timer0_mode0_ms_to_ticks_prog = env.Program(
    'timer0_mode0_ms_to_ticks_example',
    ['timer0_mode0_ms_to_ticks_example.c']
)

timer0_mode0_ticks_to_ms_prog = env.Program(
    'timer0_mode0_ticks_to_ms_example',
    ['timer0_mode0_ticks_to_ms_example.c']
)

timer0_mode0_ticks_to_Hz_prog = env.Program(
    'timer0_mode0_ticks_to_Hz_example',
    ['timer0_mode0_ticks_to_Hz_example.c']
)

timer0_mode0_Hz_to_ticks_prog = env.Program(
    'timer0_mode0_Hz_to_ticks_example',
    ['timer0_mode0_Hz_to_ticks_example.c']
)

timer0_mode0_start_ms_prog = env.Program(
    'timer0_mode0_start_ms_example',
    ['timer0_mode0_start_ms_example.c']
)

timer0_mode0_start_Hz_prog = env.Program(
    'timer0_mode0_start_Hz_example',
    ['timer0_mode0_start_Hz_example.c']
)

timer0_mode0_delay_ms_prog = env.Program(
    'timer0_mode0_delay_ms_example',
    ['timer0_mode0_delay_ms_example.c']
)

env.Default(
    timer0_mode0_ms_to_ticks_prog,
    timer0_mode0_ticks_to_ms_prog,
    timer0_mode0_ticks_to_Hz_prog,
    timer0_mode0_Hz_to_ticks_prog,
    timer0_mode0_start_ms_prog,
    timer0_mode0_start_Hz_prog,
    timer0_mode0_delay_ms_prog
)

Return([
    'timer0_mode0_ms_to_ticks_prog',
    'timer0_mode0_ticks_to_ms_prog',
    'timer0_mode0_ticks_to_Hz_prog',
    'timer0_mode0_Hz_to_ticks_prog',
    'timer0_mode0_start_ms_prog',
    'timer0_mode0_start_Hz_prog',
    'timer0_mode0_delay_ms_prog'
])
