Import('env')

env.Default(
    env.Program(
        'timer0_mode2_12T_interrupt_example',
        ['timer0_mode2_12T_interrupt_example.c']
    ),

    env.Program(
        'timer0_mode2_direct_reload_example',
        ['timer0_mode2_direct_reload_example.c']
    ),

    env.Program(
        'timer0_mode2_direct_start_example',
        ['timer0_mode2_direct_start_example.c']
    ),
)