Import('env')

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

env.Default(
    env.Program(
        'timer0_1T_freq_uint16_example',
        ['timer0_1T_freq_uint16_example.c', 'uart.c']
    ),
    
    env.Program(
        'timer0_12T_freq_uint8_example',
        ['timer0_12T_freq_uint8_example.c', 'uart.c']
    ),    

    env.Program(
        'timer0_12T_freq_uint16_example',
        ['timer0_12T_freq_uint16_example.c', 'uart.c']
    ),  

    env.Program(
        'timer0_12T_ticks_example',
        ['timer0_12T_ticks_example.c', 'uart.c']
    ),    

    env.Program(
        'timer0_ticks_to_ms_example',
        ['timer0_ticks_to_ms_example.c', 'uart.c']
    ),    

)