Import('env')

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))
env.Command('ticks_to_ms_common.c', '#src/ticks_to_ms_common.c', Copy('$TARGET', '$SOURCE'))
env.Command('timer_ticks_to_Hz.c', '#src/timer_ticks_to_Hz.c', Copy('$TARGET', '$SOURCE'))
env.Command('timer_Hz_to_ticks.c', '#src/timer_Hz_to_ticks.c', Copy('$TARGET', '$SOURCE'))

env.Default(
    env.Program(
        'timer0_mode0_Hz_to_ticks_example',
        ['timer0_mode0_Hz_to_ticks_example.c', 
         'uart.c', 
         'timer_ticks_to_Hz.c',
        ]
    ),
    
    env.Program(
        'timer0_12T_freq_uint8_example',
        ['timer0_12T_freq_uint8_example.c', 
         'uart.c', 
         'ticks_to_ms_common.c',
         'timer_ticks_to_Hz.c',
        ]
    ),    

    env.Program(
        'timer0_12T_freq_uint16_example',
        ['timer0_12T_freq_uint16_example.c', 
         'uart.c', 
         'ticks_to_ms_common.c',
         'timer_ticks_to_Hz.c',
        ]
    ),  

    env.Program(
        'timer0_12T_ticks_example',
        ['timer0_12T_ticks_example.c', 
         'uart.c', 
         'ticks_to_ms_common.c',
         'timer_ticks_to_Hz.c',
         'timer_Hz_to_ticks.c'
        ]
    ),    
)