Import('env')

env.Default(
    env.Object(
        source = 'timer0_mode3_1T_sync_example.c',
        target = 'timer0_mode3_1T_sync_example.rel'
    ),

    env.Object(
        source = 'timer0_mode3_12T_sync_example.c',
        target = 'timer0_mode3_12T_sync_example.rel'
    ),

)