Import('env')

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

env.Default(
    env.Program(
        'wdt_clear_example',
        ['wdt_clear_example.c']
    ),

    env.Program(
        'wdt_flag_example',
        ['wdt_flag_example.c', 'uart.c']
    ),

    env.Program(
        'wdt_start_example',
        ['wdt_start_example.c']
    ),

)