Import('env')

env.Command('uart1_mode2.c', '#src/uart1_mode2.c', Copy('$TARGET', '$SOURCE'))

env.Default(
    env.Program(
        'uart1_mode2_send_example',
        ['uart1_mode2_send_example.c', 'uart1_mode2.c'],
    ),
)