Import('env')

env.Default(
    env.Program(
        'uart1_mode2_send_9bit_example',
        ['uart1_mode2_send_9bit_example.c'],
    ),

    env.Program(
        'uart1_mode2_send_odd_parity_example',
        ['uart1_mode2_send_odd_parity_example.c'],
    ),

    env.Program(
        'uart1_mode2_receive_odd_parity_example',
        ['uart1_mode2_receive_odd_parity_example.c'],
    ),

)