import shutil
Import("env")

destination = env.subst("$BUILD_DIR") + '/examples/eeprom/eeprom_data.hex'
print(destination)

source = env.File('#examples/eeprom/eeprom_data.hex').abspath
print(source)

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))
shutil.copy(source, destination)

env.Default (
    env.Program(
        'eeprom_read_byte_example', 
        ['eeprom_read_byte_example.c', 'uart.c']
    ),

    env.Program(
        'eeprom_erase_page_example', 
        ['eeprom_erase_page_example.c', 'uart.c']
    ),

    env.Program(
        'eeprom_write_byte_example', 
        ['eeprom_write_byte_example.c', 'uart.c']
    ),
    
)