Import("env")

env.Default(
    env.Object(
        source = 'master_clock_output_example.c', 
        target = 'master_clock_output.rel'
    ),

    env.Object(
        source = 'slowdown_example.c', 
        target = 'slowdown.rel'
    )
)