Import("env")

master_clock_output_prog = env.Program(
    'master_clock_output_example', 
    ['master_clock_output_example.c']
)

slowdown_prog = env.Program('slowdown_example', ['slowdown_example.c'])

env.Default(
    master_clock_output_prog,
    slowdown_prog
)

Return([
    'master_clock_output_prog',
    'slowdown_prog',
])
