Import("env")

env.Append(
    CCFLAGS=[
        "-Iinclude"
    ]
)
verbose = int(ARGUMENTS.get('PIOVERBOSE', 0))

if verbose == 0:
    env.SetOption('silent', 1)

base_dir = env.subst("$BUILD_DIR") + "/examples"

SConscript('bits/SConscript', exports = 'env', variant_dir= base_dir + "/bits")
SConscript('chip_id/SConscript', exports = 'env', variant_dir= base_dir + '/chip_id')
SConscript('counter/SConscript', exports = 'env', variant_dir= base_dir + '/counter')
SConscript('delay/SConscript', exports = 'env', variant_dir= base_dir + '/delay')
SConscript('frequency/SConscript', exports = 'env', variant_dir= base_dir + '/frequency')
SConscript('interrupt/SConscript', exports = 'env', variant_dir= base_dir + '/interrupt')
SConscript('memory_dumper/SConscript', exports = 'env', variant_dir= base_dir + '/memory_dumper')
SConscript('power_management/SConscript', exports = 'env', variant_dir= base_dir + '/power_management')
SConscript('reset/SConscript', exports = 'env', variant_dir= base_dir + '/reset')
SConscript('timer/SConscript', exports = 'env', variant_dir= base_dir + '/timer')
SConscript('uart/SConscript', exports = 'env', variant_dir= base_dir + '/uart')
SConscript('wdt/SConscript', exports = 'env', variant_dir= base_dir + '/wdt')
SConscript('pin/SConscript', exports = 'env', variant_dir= base_dir + '/pin')
SConscript('pin/SConscript', exports = 'env', variant_dir= base_dir + '/eeprom')