Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))
env.Command('ms_to_ticks_common.c', '#src/ms_to_ticks_common.c', Copy('$TARGET', '$SOURCE'))

env.Default(
    env.Program(
        'timer0_common_example',
        ['timer0_common_example.c', 'uart.c']
    ),

    env.Program(
        'timer0_mode0_ms_to_ticks_example',
        ['timer0_mode0_ms_to_ticks_example.c', 'uart.c', 'ms_to_ticks_common.c']
    ),

    env.Program(
        'timer0_mode1_ms_to_ticks_example',
        ['timer0_mode1_ms_to_ticks_example.c', 'uart.c', 'ms_to_ticks_common.c']
    ),

    env.Program(
        'timer0_mode2_ms_to_ticks_example',
        ['timer0_mode2_ms_to_ticks_example.c', 'uart.c', 'ms_to_ticks_common.c']
    ),

    env.Program(
        'timer0_mode3_ms_to_ticks_example',
        ['timer0_mode3_ms_to_ticks_example.c', 'uart.c', 'ms_to_ticks_common.c']
    ),

    env.Program(
        'timer2_common_example',
        ['timer2_common_example.c', 'uart.c']
    ),

    env.Program(
        'timer2_mode0_ms_to_ticks_example',
        ['timer2_mode0_ms_to_ticks_example.c', 'uart.c', 'ms_to_ticks_common.c']
    ),
)