Import("env")

env.Default(
    env.Object(
        source = 'timer0_common_example.c',
        target = 'timer0_common_example.rel'
    ),

    env.Object(
        source = 'timer0_ms2ticks_example.c',
        target = 'timer0_ms2ticks_example.rel'
    ),

    env.Object(
        source = 'timer2_common_example.c',
        target = 'timer2_common_example.rel'
    ),

)