Import("env")

env.Default(
    env.Program(
        'timer0_common_example',
        ['timer0_common_example.c', 'uart.c']
    ),

    env.Program(
        'timer0_ms2ticks_example',
        ['timer0_ms2ticks_example.c', 'uart.c']
    ),

    env.Object(
        source = 'timer2_common_example.c',
        target = 'timer2_common_example.rel'
    ),

)