Import('env')

env.Default(
    env.Program(
        'uart1_mode0_send_example',
        ['uart1_mode0_send_example.c']
    ),

    env.Program(
        'uart1_mode0_baud_rates_example',
        ['uart1_mode0_baud_rates_example.c']
    ),

)