Import('env')

env.Command(
    'uart1_mode1_timer2_12T_ext.c',
    '#src/uart1_mode1_timer2_12T_ext.c',
    Copy('$TARGET', '$SOURCE'))

env.Default(
    env.Program(
        'uart1_mode1_timer2_12T_example',
        ['uart1_mode1_timer2_12T_example.c']
    ),

    env.Program(
        'uart1_mode1_timer2_12T_interrupt_example',
        ['uart1_mode1_timer2_12T_interrupt_example.c']
    ),

    env.Program(
        'uart1_mode1_timer2_12T_freq_bias_example',
        ['uart1_mode1_timer2_12T_freq_bias_example.c']
    ),

    env.Program(
        'uart1_mode1_timer2_1T_example',
        ['uart1_mode1_timer2_1T_example.c']
    ),

)