Import("env")

timer2_mode0_start_ms_prog = env.Program(
    'timer2_mode0_start_ms_example',
    ['timer2_mode0_start_ms_example.c']
)

timer2_mode0_start_Hz_prog = env.Program(
    'timer2_mode0_start_Hz_example',
    ['timer2_mode0_start_Hz_example.c']
)

env.Default(
    timer2_mode0_start_ms_prog,
    timer2_mode0_start_Hz_prog
)

Return([
    'timer2_mode0_start_ms_prog',
    'timer2_mode0_start_Hz_prog'
])
