Import("env")

counter0_mode2_prog = env.Program(
    'counter0_mode2_example',
    [
        'counter0_mode2_example.c',
    ]
)

counter0_mode2_p35_output_prog = env.Program(
    'counter0_mode2_p35_output_example',
    ['counter0_mode2_p35_output_example.c'],
)

counter0_mode2_gate_prog = env.Program(
    'counter0_mode2_gate_example',
    ['counter0_mode2_gate_example.c']
)

env.Default(
    counter0_mode2_prog,
    counter0_mode2_p35_output_prog,
    counter0_mode2_gate_prog
)

Return([
    'counter0_mode2_prog',
    'counter0_mode2_p35_output_prog',
    'counter0_mode2_gate_prog'
])
