Import("env")


env.Default(
    env.Program(
        'counter0_mode2_example',
        [
            'counter0_mode2_example.c',
            'uart.c',
        ]
    ),

        env.Program(
        'counter0_mode2_p35_output_example',
        ['counter0_mode2_p35_output_example.c', 'uart.c'],
    ),

)