Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

env.Default(
    env.Program(
        'counter0_mode2_example',
        [
            'counter0_mode2_example.c',
            'uart.c',
        ]
    ),

        env.Program(
        'counter0_mode2_p35_output_example',
        ['counter0_mode2_p35_output_example.c', 'uart.c'],
    ),
   env.Program(
        'counter0_mode2_gate_example',
        ['counter0_mode2_gate_example.c']
    )

)