Import("env")

env.Default(
    env.Program(
        'timer2_mode0_1T_interrupt_example',
        ['timer2_mode0_1T_interrupt_example.c']
    ),

    env.Program(
        'timer2_mode0_P30_output_example',
        ['timer2_mode0_P30_output_example.c']
    ),

    env.Program(
        'timer2_mode0_reload_example',
        ['timer2_mode0_reload_example.c']
    ),

    env.Program(
        'timer2_mode0_direct_reload_example',
        ['timer2_mode0_direct_reload_example.c']
    ),    

)