Import("env")

env.Append(
    CCFLAGS=[
        "-Iinclude"
    ]
)
verbose = int(ARGUMENTS.get('PIOVERBOSE', 0))

if verbose == 0:
    env.SetOption('silent', 1)

base_dir = env.subst("$BUILD_DIR") + "/utils"

SConscript('memory_dumper/SConscript', exports = 'env', variant_dir= base_dir + "/bits")