Import("env")

mode0_prog = SConscript('mode0/SConscript', exports = 'env')
mode1_prog = SConscript('mode1/SConscript', exports = 'env')
mode2_prog = SConscript('mode2/SConscript', exports = 'env')
mode3_prog = SConscript('mode3/SConscript', exports = 'env')

Return([
    'mode0_prog',
    'mode1_prog',
    'mode2_prog',
    'mode3_prog',
])