Import("env")

interrupt_int0_prog = env.Program('interrupt_int0_example', ['interrupt_int0_example.c'])
interrupt_int1_prog = env.Program('interrupt_int1_example', ['interrupt_int1_example.c'])

env.Default(interrupt_int0_prog, interrupt_int1_prog)

Return([
    'interrupt_int0_prog',
    'interrupt_int1_prog',
])