Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

env.Default(
    env.Program(
        "pin_read_value_example",
        ["pin_read_value_example.c", 'uart.c']
    ),
)