Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

counter0_mode1_prog = env.Program(
    'counter0_mode1_example',
    [
        'counter0_mode1_example.c',
        'uart.c',
    ]
)

env.Default(counter0_mode1_prog)
