Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

env.Default (
    env.Program(
        'timer2_12T_freq_uint16_example', 
        ['timer2_12T_freq_uint16_example.c', 'uart.c']
    ),

    env.Program(
        'timer2_ticks_to_ms_example', 
        ['timer2_ticks_to_ms_example.c', 'uart.c']
    ),

    env.Program(
        'timer2_uart_baud_rate_example', 
        ['timer2_uart_baud_rate_example.c', 'uart.c']
    ),

)