Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))
env.Command('ticks_to_ms_common.c', '#src/ticks_to_ms_common.c', Copy('$TARGET', '$SOURCE'))

env.Default (
    env.Program(
        'timer2_12T_freq_uint16_example', 
        ['timer2_12T_freq_uint16_example.c', 'uart.c', 'ticks_to_ms_common.c']
    ),

    env.Program(
        'timer2_ticks_to_ms_example', 
        ['timer2_ticks_to_ms_example.c', 'uart.c', 'ticks_to_ms_common.c']
    ),

)