Import('env')

env.Default(
    env.Object(
        source = 'timer0_mode2_1T_sync_example.c',
        target = 'timer0_mode2_1T_sync_example.rel'
    ),

    env.Object(
        source = 'timer0_mode2_12T_sync_example.c',
        target = 'timer0_mode2_12T_sync_example.rel'
    ),
)