Import('env')

env.Default(
    env.Program(
        'timer0_mode2_1T_sync_example',
        ['timer0_mode2_1T_sync_example.c']
    ),

    env.Program(
        'timer0_mode2_12T_sync_example',
        ['timer0_mode2_12T_sync_example.c']
    ),
)