Import('env')

env.Default(
    env.Program(
        'timer0_mode1_1T_interrupt_example',
        ['timer0_mode1_1T_interrupt_example.c']
    ),

    env.Program(
        'timer0_mode1_pause_by_gate_example',
        ['timer0_mode1_pause_by_gate_example.c']
    ),

    env.Program(
        'timer0_mode1_direct_start_example',
        ['timer0_mode1_direct_start_example.c']
    ),

)