Import('env')

env.Default(
    env.Object(
        source = 'timer0_mode1_1T_interrupt_example.c',
        target = 'timer0_mode1_1T_interrupt_example.rel'
    ),

    env.Object(
        source = 'timer0_mode1_pause_by_gate_example.c',
        target = 'timer0_mode1_pause_by_gate_example.rel'
    ),

    env.Object(
        source = 'timer0_mode1_direct_start_example.c',
        target = 'timer0_mode1_direct_start_example.rel'
    ),

)