Import("env")

timer0_mode1_1T_interrupt_prog = env.Program(
    'timer0_mode1_1T_interrupt_example',
    ['timer0_mode1_1T_interrupt_example.c']
)

timer0_mode1_pause_by_gate_prog = env.Program(
    'timer0_mode1_pause_by_gate_example',
    ['timer0_mode1_pause_by_gate_example.c']
)

timer0_mode1_direct_start_prog = env.Program(
    'timer0_mode1_direct_start_example',
    ['timer0_mode1_direct_start_example.c']
)

env.Default(
    timer0_mode1_1T_interrupt_prog,
    timer0_mode1_pause_by_gate_prog,
    timer0_mode1_direct_start_prog
)

Return([
    'timer0_mode1_1T_interrupt_prog',
    'timer0_mode1_pause_by_gate_prog',
    'timer0_mode1_direct_start_prog'
])
