Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

env.Default (
    env.Program(
        'counter0_mode3_example', 
        [
            'counter0_mode3_example.c', 
            'uart.c'
        ]
    ), 

    env.Program(
        'counter0_mode3_p35_output_example',
        ['counter0_mode3_p35_output_example.c']
    ),

    env.Program(
        'counter0_mode3_gate_example',
        ['counter0_mode3_gate_example.c']
    )
)