Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

counter0_mode3_prog = env.Program(
    'counter0_mode3_example', 
    [
        'counter0_mode3_example.c', 
        'uart.c'
    ]
)

counter0_mode3_p35_output_prog = env.Program(
    'counter0_mode3_p35_output_example',
    ['counter0_mode3_p35_output_example.c']
)

counter0_mode3_gate_prog = env.Program(
    'counter0_mode3_gate_example',
    ['counter0_mode3_gate_example.c']
)

env.Default(
    counter0_mode3_prog,
    counter0_mode3_p35_output_prog,
    counter0_mode3_gate_prog
)
