Import("env")

SConscript('simple/SConscript', exports = 'env')
SConscript('mode0/SConscript', exports = 'env')
SConscript('mode1/SConscript', exports = 'env')
SConscript('mode2/SConscript', exports = 'env')