Import("env")

env.Default(
    env.Program(
        'timer0_mode0_1T_interrupt_example',
        ['timer0_mode0_1T_interrupt_example.c']
    ),

    env.Program(
        'timer0_mode0_12T_interrupt_example',
        ['timer0_mode0_12T_interrupt_example.c']
    ),

    env.Program(
        'timer0_mode0_direct_reload_example',
        ['timer0_mode0_direct_reload_example.c']
    ),

    env.Object(
        source = 'timer0_mode0_pause_by_gate_example.c',
        target = 'timer0_mode0_pause_by_gate_example.rel'
    ),

    env.Object(
        source = 'timer0_mode0_reload_example.c',
        target = 'timer0_mode0_reload_example.rel'
    ),

    env.Object(
        source = 'timer0_mode0_direct_start_example.c',
        target = 'timer0_mode0_direct_start_example.rel'
    ),

)