Import("env")

env.Default(
    env.Program(
        'timer0_mode0_1T_interrupt_example',
        ['timer0_mode0_1T_interrupt_example.c']
    ),

    env.Program(
        'timer0_mode0_12T_interrupt_example',
        ['timer0_mode0_12T_interrupt_example.c']
    ),

    env.Program(
        'timer0_mode0_direct_reload_example',
        ['timer0_mode0_direct_reload_example.c']
    ),

    env.Program(
        'timer0_mode0_pause_by_gate_example',
        ['timer0_mode0_pause_by_gate_example.c']
    ),

    env.Program(
        'timer0_mode0_reload_example',
        ['timer0_mode0_reload_example.c']
    ),

    env.Program(
        'timer0_mode0_direct_start_example',
        ['timer0_mode0_direct_start_example.c']
    ),

)