Import("env")

timer0_mode0_1T_interrupt_prog = env.Program(
    'timer0_mode0_1T_interrupt_example',
    ['timer0_mode0_1T_interrupt_example.c']
)

timer0_mode0_12T_interrupt_prog = env.Program(
    'timer0_mode0_12T_interrupt_example',
    ['timer0_mode0_12T_interrupt_example.c']
)

timer0_mode0_direct_reload_prog = env.Program(
    'timer0_mode0_direct_reload_example',
    ['timer0_mode0_direct_reload_example.c']
)

timer0_mode0_pause_by_gate_prog = env.Program(
    'timer0_mode0_pause_by_gate_example',
    ['timer0_mode0_pause_by_gate_example.c']
)

timer0_mode0_reload_prog = env.Program(
    'timer0_mode0_reload_example',
    ['timer0_mode0_reload_example.c']
)

timer0_mode0_direct_start_prog = env.Program(
    'timer0_mode0_direct_start_example',
    ['timer0_mode0_direct_start_example.c']
)

env.Default(
    timer0_mode0_1T_interrupt_prog,
    timer0_mode0_12T_interrupt_prog,
    timer0_mode0_direct_reload_prog,
    timer0_mode0_pause_by_gate_prog,
    timer0_mode0_reload_prog,
    timer0_mode0_direct_start_prog
)

Return([
    'timer0_mode0_1T_interrupt_prog',
    'timer0_mode0_12T_interrupt_prog',
    'timer0_mode0_direct_reload_prog',
    'timer0_mode0_pause_by_gate_prog',
    'timer0_mode0_reload_prog',
    'timer0_mode0_direct_start_prog'
])
