Import("env")

powerdown_prog = env.Program(
    'powerdown_example', 
    ['powerdown_example.c']
)

idle_prog = env.Program(
    'idle_example', 
    ['idle_example.c']
)

low_voltage_prog = env.Program(
    'low_voltage_example', 
    ['low_voltage_example.c']
)

wakeup_seconds_prog = env.Program(
    'wakeup_seconds_example', 
    ['wakeup_seconds_example.c']
)

env.Default(
    powerdown_prog,
    idle_prog,
    low_voltage_prog,
    wakeup_seconds_prog
)

Return([
    'powerdown_prog',
    'idle_prog',
    'low_voltage_prog',
    'wakeup_seconds_prog',
])
