Import("env")

env.Default (
    env.Program(
        'powerdown_example', 
        ['powerdown_example.c', 'uart.c']
    ),
    env.Program(
        'idle_example', 
        ['idle_example.c', 'uart.c']
    )
)