Import("env")

env.Command('uart.c', '#src/uart.c', Copy('$TARGET', '$SOURCE'))

env.Default (
    env.Program(
        'powerdown_example', 
        ['powerdown_example.c', 'uart.c']
    ),
    env.Program(
        'idle_example', 
        ['idle_example.c', 'uart.c']
    )
)