name: CMake build release

on:
  push:
    tags:
      - 'v*'
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

concurrency:
  group: "deploy-release"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install sdcc and tools
        run: |
          sudo apt-get update
          sudo apt-get install -y sdcc graphviz doxygen

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}

      - name: Package distribution
        working-directory: ${{github.workspace}}
        run: |  
          mkdir -p ${{github.workspace}}/dist/include
          mkdir -p ${{github.workspace}}/dist/lib
          find build/src -name '*.lib' -exec cp {} dist/lib \;
          cp include/*.h dist/include
          cd dist && zip -r ../STC15lib-${{ github.ref_name }}.zip .

  build-pages:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Build Documentation with Doxygen
        run: doxygen doxygen.conf

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Add .nojekyll
        run: touch docs/html/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/html

  deploy-pages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5