set(CMAKE_ASM_OUTPUT_EXTENSION .rel)
set(CMAKE_ASMSDAS8051_OUTPUT_EXTENSION .rel)
set(CMAKE_ASM_OUTPUT_EXTENSION_REPLACE 1)


if(NOT DEFINED CMAKE_ASM_FLAGS_INIT)
    set(CMAKE_ASM_FLAGS_INIT "")
endif()


set(CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <FLAGS> <OBJECT> <SOURCE>")
set(CMAKE_ASM_LINK_EXECUTABLE 
	"${CMAKE_ASM_COMPILER_LINKER} <CMAKE_ASM_LINK_FLAGS> <TARGET> <OBJECTS>"
	"\"${CMAKE_COMMAND}\" -E echo This is ASM)"
)


# needs sdcc + sdar/sdcclib
set(CMAKE_ASM_CREATE_STATIC_LIBRARY
      "\"${CMAKE_COMMAND}\" -E remove <TARGET>"
      "<CMAKE_AR> ${CMAKE_AR_OPTIONS} <TARGET> <LINK_FLAGS> <OBJECTS> ")

set(CMAKE_ASM_CREATE_SHARED_LIBRARY "")
set(CMAKE_ASM_CREATE_MODULE_LIBRARY "")

